export const userInitialState = {
    name: '',
    email: '',
    image: '',
    mobile: '',
    birthDate: '',
    password: '',
    gender: '',
    state: '',
    district: '',
    role: 'member',
    userCategory: 'reader', 
    art: '',
    objective: 'joined to empower the society!',
    isActive: true, 
    createdAt: new Date().toLocaleString(),
    updatedAt: new Date().toLocaleString(), 
};
